-- MySQL Script generated by MySQL Workbench
-- Fri Jul 17 18:56:15 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema library_z
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema library_z
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library_z` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `library_z` ;

-- -----------------------------------------------------
-- Table `library_z`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_z`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `nfc_id` VARCHAR(16) NOT NULL,
  `cw_user_id` VARCHAR(45) NOT NULL,
  `image` TEXT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nfc_id_UNIQUE` (`nfc_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_z`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_z`.`book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `isbn` INT NULL,
  `publisher` VARCHAR(32) NULL,
  `category` VARCHAR(32) NULL,
  `category_number` INT NULL,
  `place` VARCHAR(16) NULL,
  `image` TEXT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `deleted_at` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_z`.`borrowing_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_z`.`borrowing_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  `return_date` DATE NOT NULL,
  `cw_task_id` INT NULL,
  `is_finished` TINYINT(1) NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`user_id` ASC),
  INDEX `book_id_idx` (`book_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `library_z`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `book_id`
    FOREIGN KEY (`book_id`)
    REFERENCES `library_z`.`book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
