-- MySQL Script generated by MySQL Workbench
-- Wed Jul 22 15:41:21 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema library_z
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `library_z` ;

-- -----------------------------------------------------
-- Schema library_z
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library_z` DEFAULT CHARACTER SET utf8mb4;
USE `library_z` ;

-- -----------------------------------------------------
-- Table `library_z`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_z`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL,
  `nfc_device_id` VARCHAR(16) NULL,
  `chatwork_api_token` VARCHAR(128) NULL,
  `image` TEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` VARCHAR(45) NULL,
  `deleted_at` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_z`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_z`.`book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NULL,
  `isbn` VARCHAR(32) NULL,
  `publisher` VARCHAR(32) NULL,
  `category` VARCHAR(32) NULL,
  `category_id` INT NULL,
  `place` VARCHAR(16) NULL,
  `image` TEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_z`.`borrowing_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_z`.`borrowing_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `book_id` INT NULL,
  `return_date` DATE NULL,
  `chatwork_task_id` INT NULL,
  `finish` TINYINT(1) NULL DEFAULT 0,
  `created_at` DATETIME NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`user_id` ASC),
  INDEX `book_id_idx` (`book_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `library_z`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `book_id`
    FOREIGN KEY (`book_id`)
    REFERENCES `library_z`.`book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
